---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: uptest-cron
spec:
  schedule: "*/15 * * * *"
  startingDeadlineSeconds: 180
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: service
              {{ with .Values.image }}
              image: {{ .registry }}/{{ .imagePrefix | default "polymny" }}/uptest:{{ .tag | default "latest" }}
              {{- end }}
              env:
                - name: USERNAME
                  value: {{ .Values.uptest.username }}
                - name: HOST
                  value: {{ .Values.uptest.host }}
                - name: PORT
                  value: {{ .Values.uptest.port | quote }}
                - name: DEST
                  value: {{ .Values.uptest.dest }}
                - name: PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: uptest
                      key: password
                - name: URLS
                  value: {{ join " " .Values.uptest.urls }}
                {{- if .Values.uptest.s3 }}
                - name: S3_ENDPOINT
                  value: {{ .Values.uptest.s3.endpoint }}
                - name: S3_REGION
                  value: {{ .Values.uptest.s3.region }}
                - name: S3_BUCKET
                  value: {{ .Values.uptest.s3.bucket }}
                - name: S3_KEY
                  value: {{ .Values.uptest.s3.key }}
                - name: S3_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: s3
                      key: secret
                {{- end }}
          imagePullSecrets:
            - name: registry-credentials

